src/AppBundle/Entity/Customer.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * User
 *
 * @ORM\Table(name="customer")
 * @ORM\Entity
 */
class Customer
{
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Company", inversedBy="customers")
     * @ORM\JoinColumn(name="company_id", referencedColumnName="id", nullable=false)
     *
     * @var AppBundle\Entity\Company;
     */
    protected $company;  
    
    /**
     * @var float
     * @ORM\Column(name="old", type="integer", nullable=false)
     */    
    protected $old=0;

    /**
     * @var float
     * @ORM\Column(name="old_location", type="integer", nullable=true)
     */
    protected $old_Location=0;

    /**
     * @var string
     * @ORM\Column(type="string", length=8, nullable=true, name="locale")
     */
    protected $locale;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="firstname")
     */
    protected $firstname;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="lastname")
     */
    protected $lastname;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="firstname_location")
     */
    protected $firstname_location;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="lastname_location")
     */
    protected $lastname_location;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="email")
     */
    protected $email;

    /**
     * @var string
     * @ORM\Column(name="vat", type="string", length=128, nullable=true)
     * @Assert\Length(
     *             min=3,
     *             max=128)
     */
    protected $vat;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="adress1")
     * @Assert\Length(
     *             min=3,
     *             max=255)
     */
    protected $adress1;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="adress2")
     */
    protected $adress2;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="adress3")
     */
    protected $adress3;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="zip")
     * @Assert\Length(
     *             min=3,
     *             max=255)
     */
    protected $zip;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="city")
     * @Assert\Length(
     *             min=3,
     *             max=255)
     */
    protected $city;

    /**
     * @var string
     * @ORM\Column(type="string", length=5, nullable=true, name="country")
     */
    protected $country;


    public function __construct()
    {
        $this->locale = 'en_GB';
        $this->country = 'BE';
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getInvoicename()
    {
        $name='';
        if ($this->getLastname() OR $this->getLastnameLocation()) {
            if ($this->getLastnameLocation()) {
                $name = $this->getLastnameLocation();
            } else {
                $name = $this->getLastname();
            }
            if ($this->getFirstnameLocation()) {
                $name = $name . ' ' . $this->getFirstnameLocation();
            } else {
                if ($this->getFirstname()) {
                    $name = $name . ' ' . $this->getFirstname();
                }
            }
        } else {
            if ($this->getFirstnameLocation()) {
                $name = $this->getFirstnameLocation();
            }else {
                if ($this->getFirstname()) {
                    $name = $this->getFirstname();
                }
            }
        }
        return $name;
    }
        
    public function getName()
    {   
        $name='';
        if ($this->getLastname()) {
            $name = $this->getLastname(); 
            if ($this->getFirstname()) {
                $name = $name.' '.$this->getFirstname();
            }
        } else {
            if ($this->getFirstname()) {
                $name= $this->getFirstname();
            }
        }
        return $name;
    }    
    
    public function getFullname()
    {
        $fullname = $this->getName();
        if ($this->getCompany()->getId() === 15) {
            if ($this->getCity()) {
                return $fullname . ' | ' . trim($this->getAdress1() . ' ' . $this->getCity());
            } else {
                return $fullname;
            }
        } else {
            if ($fullname) {
                $fullname = $fullname.' ('.trim($this->getAdress1().' '.$this->getCity()).' | '.strtoupper($this->getCompany()->getName()).')';
            } else {
                $fullname = trim($this->getAdress1().' '.$this->getCity()).' | '.strtoupper($this->getCompany()->getName());
            }
        }
        return $fullname;
        
    }      
    
    public function __toString()
    {
        return $this->getName();
    }    
    
    /**
     * Set user
     *
     * @param \AppBundle\Entity\Company $company
     * @return Company
     */
    public function setCompany(\AppBundle\Entity\Company $company = null)
    {
        $this->company = $company;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\Company 
     */
    public function getCompany()
    {
        return $this->company;
    }    

  
    function getOld() {
        return $this->old;
    }

    function setOld($old) {
        $this->old = $old;
    }

    /**
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * @param string $firstname
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    /**
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param string $lastname
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getVat()
    {
        return $this->vat;
    }

    /**
     * @param string $vat
     */
    public function setVat($vat)
    {
        $this->vat = $vat;
    }

    /**
     * @return string
     */
    public function getAdress1()
    {
        return $this->adress1;
    }

    /**
     * @param string $adress1
     */
    public function setAdress1($adress1)
    {
        $this->adress1 = $adress1;
    }

    /**
     * @return string
     */
    public function getAdress2()
    {
        return $this->adress2;
    }

    /**
     * @param string $adress2
     */
    public function setAdress2($adress2)
    {
        $this->adress2 = $adress2;
    }

    /**
     * @return string
     */
    public function getAdress3()
    {
        return $this->adress3;
    }

    /**
     * @param string $adress3
     */
    public function setAdress3($adress3)
    {
        $this->adress3 = $adress3;
    }

    /**
     * @return string
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * @param string $zip
     */
    public function setZip($zip)
    {
        $this->zip = $zip;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param string $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * @return float
     */
    public function getOldLocation()
    {
        return $this->old_Location;
    }

    /**
     * @param float $old_Location
     */
    public function setOldLocation($old_Location)
    {
        $this->old_Location = $old_Location;
    }

    /**
     * @return string
     */
    public function getFirstnameLocation()
    {
        return $this->firstname_location;
    }

    /**
     * @param string $firstname_location
     */
    public function setFirstnameLocation($firstname_location)
    {
        $this->firstname_location = $firstname_location;
    }

    /**
     * @return string
     */
    public function getLastnameLocation()
    {
        return $this->lastname_location;
    }

    /**
     * @param string $lastname_location
     */
    public function setLastnameLocation($lastname_location)
    {
        $this->lastname_location = $lastname_location;
    }

    /**
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * @param string $locale
     */
    public function setLocale($locale)
    {
        $this->locale = $locale;
    }




    
}
/**

src/AppBundle/Controller/CreditController.php
<?php

namespace AppBundle\Controller;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Sonata\AdminBundle\Controller\CRUDController as Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Swift_Attachment;


use AppBundle\Entity\Invoice;
use AppBundle\Entity\Credit;
use AppBundle\Entity\Reminder;
use AppBundle\Entity\Erase;


class CreditController extends Controller
{
    public function paidAction()
    {
        $object = $this->admin->getSubject();

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $id));
        }

        $object->setStatus(Invoice::STATUS_CLOSED);
        $object->setPaiement(new \DateTime());

        $this->admin->update($object);

        $this->addFlash('sonata_flash_success', 'Update successfully');

        return new RedirectResponse($this->admin->generateUrl('list'));
    }
    
    public function printAction()
    {
        $object = $this->admin->getSubject();

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $id));
        }
        
        $translator = $this->get('translator');
        $sessionLocale = $translator->getLocale();

        $translator->setLocale($object->getCustomer()->getLocale());

        $html = $this->renderView('AppBundle:Credit:pdf.html.twig', array(
             'credit'  => $object
        ));
        

        $translator->setLocale($sessionLocale);

        return new Response(
            $this->get('knp_snappy.pdf')->getOutputFromHtml($html, array('page-size' => 'A4','lowquality' => false)),
            200,
            array(
                'Content-Type'          => 'application/pdf',
                'Content-Disposition'   => 'attachment; filename="'.$object->getCreditNumber().'.pdf"'
            )
        );        
    }  
    
    public function eraseAction($id) {
        $object = $this->admin->getSubject();

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $id));
        }
        
        $em = $this->getDoctrine()->getManager();
        
        if ($object->getCreditNumber()) {
            $old = new Erase();
            $old->setType(Erase::TYPE_CREDIT);
            $old->setNumber($object->getCreditNumber());
            $em->persist($old);
            $em->flush();            
        }
        
        $this->admin->delete($object); 
        
        $this->addFlash('sonata_flash_success', 'Update successfully');

        return new RedirectResponse($this->admin->generateUrl('list'));        
    }
    
    public function openAction()
    {
        $object = $this->admin->getSubject();

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $id));
        }
        
        $em = $this->getDoctrine()->getManager();
        if (!$creditNr = $em->getRepository('AppBundle:Erase')->findandRemoveOldNumber(Erase::TYPE_CREDIT)) {
            $lastCredit = $em->getRepository('AppBundle:Credit')->findLastNumber(); 
            if ($lastCredit) {
                $creditNr = $lastCredit->getCreditNumber() + 1;
            } else {
                $creditNr = date("y") . " " . sprintf('%06s', 1);
            }
        }       
                
        if ($object->getStatus() == Credit::STATUS_NEW) {
            $object->setStatus(Credit::STATUS_OPEN);
            $object->setCreditNumber($creditNr);
        }

        $this->admin->update($object);     
        
        $translator = $this->get('translator');
        $sessionLocale = $translator->getLocale();

        $translator->setLocale($object->getCustomer()->getLocale());

        $html = $this->renderView('AppBundle:Credit:pdf.html.twig', array(
             'credit'  => $object
        ));
        

        $translator->setLocale($sessionLocale);

        return new Response(
            $this->get('knp_snappy.pdf')->getOutputFromHtml($html, array('page-size' => 'A4','lowquality' => false)),
            200,
            array(
                'Content-Type'          => 'application/pdf',
                'Content-Disposition'   => 'attachment; filename="'.$object->getCreditNumber().'.pdf"'
            )
        );

        
    }    
    
    
    public function sendAction()
    {
        $object = $this->admin->getSubject();

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $id));
        }
        
        $em = $this->getDoctrine()->getManager();
        if (!$creditNr = $em->getRepository('AppBundle:Erase')->findandRemoveOldNumber(Erase::TYPE_CREDIT)) {
            $lastCredit = $em->getRepository('AppBundle:Credit')->findLastNumber(); 
            if ($lastCredit) {
                $creditNr = $lastCredit->getCreditNumber() + 1;
            } else {
                $creditNr = date("y") . " " . sprintf('%06s', 1);
            }
        }
                
        if ($object->getStatus() == Credit::STATUS_NEW) {
            $object->setStatus(Credit::STATUS_OPEN);
            $object->setCreditNumber($creditNr);
        }

        $this->admin->update($object);
        
        if ($object->getCustomer()->getEmail() != '')
        {
            $translator = $this->get('translator');
            $sessionLocale = $translator->getLocale();

            $translator->setLocale($object->getCustomer()->getLocale());

            $path = __DIR__.'/../../../web/doc/'.$object->getCreditNumber().'.pdf';

            $this->get('knp_snappy.pdf')->generateFromHtml(
                $this->renderView('AppBundle:Credit:pdf.html.twig', array(
                    'credit'  => $object
                )),
                $path
            );     

            $message = \Swift_Message::newInstance()
                    ->setSubject($this->get('translator')->trans('mail.new_credit.title',array('%creditnumber%'=>$object->getCreditNumber()),'mail'))
                    ->setFrom('info@timeismoney.be', 'Time is Money bvba')
                    ->setTo($object->getCustomer()->getEmail())
                    ->setBody(
                        $this->renderView(
                            'email/newCredit.html.twig',
                            array('credit' => $object)
                        ),
                        'text/html'
                    )
                    ->attach(\Swift_Attachment::fromPath($path))
                ;
            $this->get('mailer')->send($message); 
            $translator->setLocale($sessionLocale);
            $this->addFlash('sonata_flash_success', 'Email send');
            
            unlink($path);
        }

        return new RedirectResponse($this->admin->generateUrl('list'));
    }  
    
    public function batchActionPdf(ProxyQueryInterface $selectedModelQuery, Request $request = null)
    {
        if (!$this->admin->isGranted('EDIT'))
        {
            throw new AccessDeniedException();
        }

        $selectedModels = $selectedModelQuery->execute();

        $html = '';
        foreach ($selectedModels as $selectedModel) {
            $html .= $this->renderView('AppBundle:Credit:pdf.html.twig', array(
                 'credit'  => $selectedModel
            ));

        }

        return new Response(
            $this->get('knp_snappy.pdf')->getOutputFromHtml($html, array('page-size' => 'A4','lowquality' => false)),
            200,
            array(
                'Content-Type'          => 'application/pdf',
                'Content-Disposition'   => 'attachment; filename="all.pdf"'
            )
        );
    }        
    
}

src/AppBundle/Resources/views/Credit/list__action_erase.html.twig
    <a class="btn btn-sm btn-default edit_link" href="{{ admin.generateObjectUrl('erase', object) }}">
        <i class="fa fa-trash"></i>
        {{ 'link_action_erase'|trans({}) }}</a>

src/AppBundle/Resources/views/Credit/list__action_open.html.twig
    <a class="btn btn-sm btn-default edit_link" href="{{ admin.generateObjectUrl('open', object) }}">
        <i class="fa fa-envelope"></i>
        {{ 'link_action_send_active'|trans({}) }}</a>

src/AppBundle/Resources/views/Credit/list__action_paid.html.twig
<a class="btn btn-sm btn-default edit_link" href="{{ admin.generateObjectUrl('paid', object) }}">
    <i class="fa fa-euro"></i>
    {{ 'link_action_paid'|trans({}) }}</a>

src/AppBundle/Resources/views/Credit/pdf.html.twig
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Credit</title>
                <style>
                    @font-face {
                      font-family: 'Source Sans Pro', sans-serif;
                      url: 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300';
                    }   
                    
                    .clearfix:after {
                      content: "";
                      display: table;
                      clear: both;
                    }

                    a {
                      color: #0087C3;
                      text-decoration: none;
                    }

                    body {
                      position: relative;
                      width: 21cm;  
                      height: 29.7cm; 
                      margin: 0 auto; 
                      color: #555555;
                      background: #FFFFFF; 
                      font-family: Arial, sans-serif; 
                      font-size: 10px; 
                      font-family: SourceSansPro;
                    }

                    header {
                      padding: 10px 0;
                      margin-bottom: 20px;
                      border-bottom: 1px solid #AAAAAA;
                    }

                    #logo {
                      float: left;
                      margin-top: 0px;
                    }

                    #logo img {
                      height: 140px;
                    }

                    #company {
                      float: right;
                      text-align: right;
                    }


                    #details {
                      margin-bottom: 50px;
                    }

                    #client {
                      padding-left: 6px;
                      border-left: 6px solid #0087C3;
                      float: left;
                      font-size: 1.4em;
                      text-align: left;
                    }

                    #client .to {
                      color: #777777;
                    }

                    h2.name {
                      font-size: 1.4em;
                      font-weight: normal;
                      margin: 0;
                    }

                    #invoice {
                      float: right;
                      text-align: right;
                    }

                    #invoice h1 {
                      color: #0087C3;
                      font-size: 2.4em;
                      line-height: 1em;
                      font-weight: normal;
                      margin: 0  0 10px 0;
                    }

                    #invoice .date {
                      font-size: 1.1em;
                      color: #777777;
                    }

                    table {
                      border-collapse: collapse;
                      border-spacing: 0;
                      margin-bottom: 20px;
                    }

                    table th{
                      padding: 20px;
                      background: #EEEEEE;
                      text-align: center;
                      border-bottom: 1px solid #FFFFFF;
                    }
                    
                    table td {
                      padding: 10px;
                      background: #EEEEEE;
                      text-align: center;
                      border-bottom: 1px solid #FFFFFF;
                    }

                    table th {
                      white-space: nowrap;        
                      font-weight: normal;
                    }

                    table td {
                      text-align: right;
                    }

                    table td h3{
                      color: #57B223;
                      font-size: 1.2em;
                      font-weight: normal;
                      margin: 0 0 0.2em 0;
                    }

                    table .no {

                    }

                    table .desc {
                      text-align: left;
                    }

                    table .unit {
                      background: #DDDDDD;
                    }

                    table .qty {
                    }

                    table .total {
                      background: #DDDDDD;
                    }

                    table td.unit,
                    table td.qty,
                    table td.total {
                      font-size: 1.2em;
                    }

                    table tbody tr:last-child td {
                      border: none;
                    }

                    table tfoot td {
                      padding: 10px 20px;
                      background: #FFFFFF;
                      border-bottom: none;
                      font-size: 1.2em;
                      white-space: nowrap; 
                      border-top: 1px solid #AAAAAA; 
                    }

                    table tfoot tr:first-child td {
                      border-top: none; 
                    }

                    table tfoot tr:last-child td {
                      color: #57B223;
                      font-size: 1.4em;
                      border-top: 1px solid #57B223; 

                    }

                    table tfoot tr td:first-child {
                      border: none;
                    }

                    #thanks{  
                      margin-bottom: 50px;
                    }

                    #notices{
                      padding-left: 6px;
                      border-left: 6px solid #0087C3;  
                    }

                    #notices .notice {
                      font-size: 1.2em;
                    }

                    footer {
                      color: #777777;
                      width: 100%;
                      height: 30px;
                      position: absolute;
                      bottom: 0;
                      border-top: 1px solid #AAAAAA;
                      padding: 8px 0;
                      text-align: center;
                    }
                </style>
	</head>
	<body>
            <header class="clearfix"> 
                <table style="width: 100%">
                    <tr>					
                        <td style="background: white;">
                            <h2>{% trans %}credit{% endtrans %}: {{ credit.creditNumber }}</h2>
                        </td>
                        <td style="background: white;">
                            {% trans %}invoice.created{% endtrans %}: {{ credit.created | craue_date }}
                        </td>							
                    </tr>
                </table>
                <table style="width: 75%; margin-left: 25%;">
                    <tr>
                        <td style="background: white;">
                            <div id="client">
                              <h2 class="name">{{ credit.customer.invoicename }}</h2>
                              <div class="address">{{ credit.customer.adress1 }} {{ credit.customer.adress2 }}</div>
                              <div class="address">{{ credit.customer.adress3 }} </div>
                              <div class="address">{{ credit.customer.zip }} {{ credit.customer.city }}</div>
                              <div class="email">{{ credit.customer.vat }}</div>
                              <div class="email">{{ credit.reference }}</div>
                              <div class="email"><a href="mailto:{{ credit.customer.email }}">{{ credit.customer.email }}</a></div>
                            </div>
                        </td>
                        <td style="background: white;">
                            <div id="company">
                              <h2 class="name">TIME IS MONEY BVBA</h2>
                              <div>Sluisvijverstraat 31<br>1742 Sint-Katherina-Lombeek (Ternat)</div>
                              <div>BE0470.025.871</div>
                              <div>{% trans %}invoice.contact{% endtrans %}: Roel Marissen</div>
                              <div><a href="mailto:info@timeismoney.be">info@timeismoney.be</a></div>
                            </div>                        
                        </td>
                    </tr>
                </table>
            </header>
            <main>
                <table style="width: 100%">
                    <thead>
                        <tr> 
                            <th class="desc">{% trans %}invoice.table.product{% endtrans %}</th>
                            <th class="unit">{% trans %}invoice.table.price{% endtrans %}</th>
                            <th class="qty">{% trans %}invoice.table.quantity{% endtrans %}</th>
                            <th class="total">{% trans %}invoice.table.total{% endtrans %}</th>
                            <th class="no">{% trans %}invoice.table.vat{% endtrans %}</th>                               
                        </tr>
                    </thead>
                    <tbody>
                        {% for line in credit.lines %}
                            <tr>
                                <td class="desc">{{ line.name }}</td>
                                <td class="unit">{{ line.price | craue_currency('EUR', 'fr-BE') }}</td>                                       
                                <td class="qty">{{ line.quantity }}</td>
                                <td class="total">{{ (line.price * line.quantity) | craue_currency('EUR', 'fr-BE') }}</td> 
                                <td class="no">{{ line.taxrate*100 }}</td>                                
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                      <tr>
                        <td colspan="1"></td>
                        <td colspan="2">{% trans %}invoice.total{% endtrans %}</td>
                        <td>{{ credit.total | craue_currency('EUR', 'fr-BE') }}</td>
                        <td colspan="1"></td>
                      </tr>                          
                    </tfoot>                        
                </table>
                <table style="width: 50%; border: 1px solid #AAAAAA">
                    <tbody>
                        {% if credit.getTotalVAT('0.00') < 0 %}
                            <tr style="border: 1px solid #AAAAAA">
                              <td style="background: white;">{% trans %}invoice.vat.0{% endtrans %}</td>
                              <td style="background: white;">{{ credit.getTotalWithoutVAT('0.00') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getVAT('0.00') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getTotalVAT('0.00') | craue_currency('EUR', 'fr-BE') }}</td>
                            </tr>
                        {% endif %}
                        {% if credit.getTotalVAT('0.06') < 0 %}
                            <tr style="border: 1px solid #AAAAAA">
                              <td style="background: white;">{% trans %}invoice.vat.6{% endtrans %}</td>
                              <td style="background: white;">{{ credit.getTotalWithoutVAT('0.06') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getVAT('0.06') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getTotalVAT('0.06') | craue_currency('EUR', 'fr-BE') }}</td>
                            </tr> 
                        {% endif %}
                        {% if credit.getTotalVAT('0.12') < 0 %}
                            <tr style="border: 1px solid #AAAAAA">
                              <td style="background: white;">{% trans %}invoice.vat.12{% endtrans %}</td>
                              <td style="background: white;">{{ credit.getTotalWithoutVAT('0.12') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getVAT('0.12') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getTotalVAT('0.12') | craue_currency('EUR', 'fr-BE') }}</td>
                            </tr> 
                        {% endif %}
                        {% if credit.getTotalVAT('0.21') < 0 %}
                            <tr style="border: 1px solid #AAAAAA">
                              <td style="background: white;">{% trans %}invoice.vat.21{% endtrans %}</td>
                              <td style="background: white;">{{ credit.getTotalWithoutVAT('0.21') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getVAT('0.21') | craue_currency('EUR', 'fr-BE') }}</td>
                              <td style="background: white;">{{ credit.getTotalVAT('0.21') | craue_currency('EUR', 'fr-BE') }}</td>
                            </tr> 
                        {% endif %}
                    </tbody>
                </table>            
            </main>
            <hr>
            <p style="text-align: center;">
              O.N. : BE0470.025.871 - ING : BE62 3900 5330 2161 - H.R. Brussel 639401
            </p>            
    	</body>
</html>    
<p style="page-break-after:always;"></p> 